export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const SET_EDIT_JOB = 'SET_EDIT_JOB';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

// For FAQ
export const CREATE_FAQ_BEGIN = 'CREATE_FAQ_BEGIN';
export const CREATE_FAQ_SUCCESS = 'CREATE_FAQ_SUCCESS';
export const CREATE_FAQ_ERROR = 'CREATE_FAQ_ERROR';
export const GET_FAQS_BEGIN = 'GET_FAQS_BEGIN';
export const GET_CLIENT_FAQS_BEGIN = 'GET_CLIENT_FAQS_BEGIN';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_CLIENT_FAQS_SUCCESS = 'GET_CLIENT_FAQS_SUCCESS';
export const SET_EDIT_FAQ = 'SET_EDIT_FAQ';
export const DELETE_FAQ_BEGIN = 'DELETE_FAQ_BEGIN';
export const DELETE_FAQ_ERROR = 'DELETE_FAQ_ERROR';
export const EDIT_FAQ_BEGIN = 'EDIT_FAQ_BEGIN';
export const EDIT_FAQ_SUCCESS = 'EDIT_FAQ_SUCCESS';
export const EDIT_FAQ_ERROR = 'EDIT_FAQ_ERROR';
export const CLEAR_FAQ_VALUES = 'CLEAR_FAQ_VALUES';

// For TopQuotes
export const CREATE_TOPQUOTE_BEGIN = 'CREATE_TOPQUOTE_BEGIN';
export const CREATE_TOPQUOTE_SUCCESS = 'CREATE_v_SUCCESS';
export const CREATE_TOPQUOTE_ERROR = 'CREATE_TOPQUOTE_ERROR';
export const GET_TOPQUOTES_BEGIN = 'GET_TOPQUOTES_BEGIN';
export const GET_CLIENT_TOPQUOTES_BEGIN = 'GET_CLIENT_vS_BEGIN';
export const GET_TOPQUOTES_SUCCESS = 'GET_TOPQUOTES_SUCCESS';
export const GET_CLIENT_TOPQUOTES_SUCCESS = 'GET_CLIENT_vS_SUCCESS';
export const SET_EDIT_TOPQUOTE = 'SET_EDIT_TOPQUOTE';
export const DELETE_TOPQUOTE_BEGIN = 'DELETE_TOPQUOTE_BEGIN';
export const DELETE_TOPQUOTE_ERROR = 'DELETE_TOPQUOTE_ERROR';
export const EDIT_TOPQUOTE_BEGIN = 'EDIT_TOPQUOTE_BEGIN';
export const EDIT_TOPQUOTE_SUCCESS = 'EDIT_v_SUCCESS';
export const EDIT_TOPQUOTE_ERROR = 'EDIT_TOPQUOTE_ERROR';
export const CLEAR_TOPQUOTE_VALUES = 'CLEAR_TOPQUOTE_VALUES';